dependencies:
  - name: openebs
    version: 2.0.0
    repository: https://openebs.github.io/charts
  - name: nfs-server-provisioner
    version: 1.1.1
    repository: https://kubernetes-charts.storage.googleapis.com