kubeapps:
  global:
    storageClass: "openebs-jiva-rdbox"
  useHelm3: true
  ingress:
    enabled: true
    certManager: true
    hostname: app-market.rdbox.lan
    tls: false
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    extraTls:
      - secretName: rdbox-common-tls
        hosts:
          - "*.rdbox.lan"
  frontend:
    nodeSelector:
      kubernetes.io/arch: amd64
      kubernetes.io/os: linux
  apprepository:
    initialRepos:
      - name: bot-gen
        url: https://rdbox-intec.github.io/rdbox_app_market/bot-gen
        nodeSelector:
          kubernetes.io/arch: amd64
          kubernetes.io/os: linux
      - name: manually
        url: https://rdbox-intec.github.io/rdbox_app_market/manually
        nodeSelector:
          kubernetes.io/arch: amd64
          kubernetes.io/os: linux
    nodeSelector:
      kubernetes.io/arch: amd64
      kubernetes.io/os: linux
  hooks:
    nodeSelector:
      kubernetes.io/arch: amd64
      kubernetes.io/os: linux
  kubeops:
    nodeSelector:
      kubernetes.io/arch: amd64
      kubernetes.io/os: linux
  tillerProxy:
    nodeSelector:
      kubernetes.io/arch: amd64
      kubernetes.io/os: linux
  assetsvc:
    nodeSelector:
      kubernetes.io/arch: amd64
      kubernetes.io/os: linux
  dashboard:
    nodeSelector:
      kubernetes.io/arch: amd64
      kubernetes.io/os: linux
  postgresql:
    global:
      storageClass: "openebs-jiva-rdbox"
    master: 
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
    slave:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux