dependencies:
  - name: metallb
    version: 0.12.1
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: nginx-ingress
    version: 1.41.3
    repository: https://kubernetes-charts.storage.googleapis.com
