apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-jiva-rdbox-src
  annotations:
    openebs.io/cas-type: jiva
    cas.openebs.io/config: |
      - name: ReplicaCount
        value: {{ .Values.storageClass.ReplicaCount }}
      - name: StoragePool
        value: default
      - name: TargetNodeSelector
        value: |-
            node.rdbox.com/location: hq
      - name: ReplicaNodeSelector
        value: |-
            node.rdbox.com/location: hq
provisioner: openebs.io/provisioner-iscsi